// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvb1IN32_ExpFgU0En1qdDW17HdO3T-sA',
    appId: '1:595351942655:web:58158d56f1ce2f3c82e3ca',
    messagingSenderId: '595351942655',
    projectId: 'gameco-5547c',
    authDomain: 'gameco-5547c.firebaseapp.com',
    storageBucket: 'gameco-5547c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWh3_UnpZDdmBhyBZzE3Htw4xjCyd-TBE',
    appId: '1:595351942655:android:f4a78049d5834d8682e3ca',
    messagingSenderId: '595351942655',
    projectId: 'gameco-5547c',
    storageBucket: 'gameco-5547c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwouasnBk7aMgE6tNJH_lrCYI_Ehq515Q',
    appId: '1:595351942655:ios:90b32f007361f46f82e3ca',
    messagingSenderId: '595351942655',
    projectId: 'gameco-5547c',
    storageBucket: 'gameco-5547c.firebasestorage.app',
    iosBundleId: 'com.example.gameco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwouasnBk7aMgE6tNJH_lrCYI_Ehq515Q',
    appId: '1:595351942655:ios:90b32f007361f46f82e3ca',
    messagingSenderId: '595351942655',
    projectId: 'gameco-5547c',
    storageBucket: 'gameco-5547c.firebasestorage.app',
    iosBundleId: 'com.example.gameco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvb1IN32_ExpFgU0En1qdDW17HdO3T-sA',
    appId: '1:595351942655:web:40cb8c591bbd630582e3ca',
    messagingSenderId: '595351942655',
    projectId: 'gameco-5547c',
    authDomain: 'gameco-5547c.firebaseapp.com',
    storageBucket: 'gameco-5547c.firebasestorage.app',
  );
}
